[project]
name = "photosheet"
version = "0.1.0"
description = "Create a pdf photosheet from a directory with images."
readme = "README.md"
authors = [
    { name = "billybuehl792", email = "billybuehl792@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
    "reportlab>=5.0.1",
]

[project.scripts]
photosheet = "photosheet.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
